name: commit-build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get esp-idf
        run: |
          pip3 install --upgrade pip
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v4.3.1 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh
      - name: build c3
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py --version
          idf.py set-target esp32c3
          idf.py build
      - name: pack firmware
        run: |
          pip3 install -r requirements.txt
          python3 esp32v2.py -t esp32c3 -p
          mkdir firmware
          mv *.soc firmware
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        with:
          name: c3-master
          path: firmware/